language: node_js
node_js:
    - "0.12"
    - "0.10"
#   - "0.8"   # no longer supported by iconv
#   - "0.6"   # no longer supported by async
    - "iojs-v1.8.1"
    - "iojs"

services:
    - redis-server

matrix:
    allow_failures:
        - node_js: "0.8"
        - node_js: "iojs"
#       - node_js: "0.6"

after_success:
    - npm run coveralls

sudo: false
